### ISSUE TITLE
README images

### ISSUE THREAD

**Issue by atinux** [Atinux/pjs#1]
![pjs-logo](https://cloud.githubusercontent.com/assets/904724/12781126/c3cf3478-ca72-11e5-95fb-74c7dfbe876b.jpg)

**Comment by Atinux** [comment]
![pjs logo](https://cloud.githubusercontent.com/assets/904724/12781165/fe94f61a-ca72-11e5-8f93-6ade4c52e03b.png)

**Comment by Atinux** [comment]
![pjs logo](https://cloud.githubusercontent.com/assets/904724/12781194/25ffcc5c-ca73-11e5-8f34-7e8c7c7f6b09.png)

**Comment by Atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12851043/15c3e484-cc28-11e5-98e0-e40c8f24e7bc.png)

**Comment by Atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12858469/ac44034e-cc50-11e5-8858-ad7a7b6b173a.png)

**Comment by atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12861525/4cd78f66-cc64-11e5-8dbd-0cd7bbcbc937.png)

**Comment by atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12892952/d2ad7390-ce8e-11e5-80b3-ed797db6dcc9.png)

**Comment by Atinux** [comment]
![pjs-logo-2](https://cloud.githubusercontent.com/assets/904724/12913951/995340da-cf19-11e5-887c-070e65f9c534.png)

**Comment by Atinux** [comment]
![tiger_vs_text](https://cloud.githubusercontent.com/assets/904724/12920961/eb3569ae-cf42-11e5-9f07-d4878079f78a.png)

**Comment by Atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12921219/0f20e69e-cf44-11e5-991c-97ebb2c0ebc0.png)

**Comment by atinux** [comment]
![pajamas-js-logo2](https://cloud.githubusercontent.com/assets/904724/12921222/14231c0c-cf44-11e5-8093-572e0d0f6f7f.png)

**Comment by Atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12921535/a2b8ad6e-cf45-11e5-827e-6846c15e0425.png)

**Comment by atinux** [comment]
![pajamas-js-logo](https://cloud.githubusercontent.com/assets/904724/12921622/0e206a6a-cf46-11e5-90ea-5860c0dc8f28.png)

**Comment by atinux** [comment]
![pajamas](https://cloud.githubusercontent.com/assets/904724/12924080/4cde4740-cf50-11e5-89dd-ed3dc51da3b9.png)
